/**
 * ═══ THE CORE — the only English that travels in EVERY page's bundle ═══
 *
 * These groups are read by the layout (header, footer, language picker, load-test strip,
 * the not-found boundary Next mounts everywhere), by the shared UI kit and by the pure
 * libraries (`wallet.ts`, `eip55.ts`), i.e. by code that runs on every page. Everything else lives in a sibling file and is imported ONLY by the
 * screen that reads it — see `index.ts` for why, and `scripts/check-en-split.mjs` for the
 * measurement that keeps it that way.
 *
 * 🔴 Before adding a group HERE, ask whether every page really reads it. A group that only
 * one screen needs belongs in its own file: putting it here charges all 13 pages for it.
 * `loadTest` is the one borderline case — the strip in the layout reads three of its keys,
 * so the whole group rides along; splitting those three off into `common` is a key move
 * across 30 dictionaries and was left for a later pass.
 */
export const EN_CORE = {
  common: {
    productName: '9Chain Testnet A1',
    // "running ON Avalanche" was WRONG and removed 2026-08-27 — A1 is a separate
    // network, not a subnet of Avalanche. See `vi.ts` for the measurement.
    // ⚠️ This comment used to name networkID `9001`. That number died the same day
    // the sentence was written: the public network was rebuilt into generation g0
    // (D-081) and now answers `999999999`. A comment that carries a live constant
    // rots silently — `lib/chain.ts` is the single source, and
    // `check-chain-id.mjs` is what actually holds it to the running network.
    shortDesc: "9Chain's public testnet — an independent network running the Avalanche engine",
    tagline: 'an independent network on the Avalanche engine',
    walletRejected: 'You rejected the request in your wallet. Nothing has changed.',
    // Phone browsers cannot hold a wallet extension — the only working path there is to open
    // the page INSIDE the MetaMask app (see `components/OpenInWallet.tsx`).
    noWalletMobile: 'A phone browser cannot hold a wallet extension. Open this page inside the MetaMask app instead — its built-in browser has the wallet.',
    openInMetaMask: 'Open in the MetaMask app',
    loading: 'Loading…',
    retry: 'Try again',
    copy: 'Copy',
    copied: 'Copied',
    close: 'Close',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    switchToDark: 'Switch to dark mode',
    switchToLight: 'Switch to light mode',
    skipToContent: 'Skip to main content',
    stepDone: ' — done',
    stepRunning: ' — running',
    stepFailed: ' — failed',
    stepPending: ' — pending',
  },

  footer: {
    tryIt: 'Try it',
    explore: 'Explore',
    about: 'About',
    explorer: '9Scan-A1 explorer',
    mainSite: '9Chain main site',
    opensNewTab: '(opens in a new tab)',
    navLabel: 'Footer links',
    rebuildPlan: 'Network rebuild plan',
  },

  nav: {
    home: 'Home',
    faucet: 'Get test tokens',
    launch: 'Launch a chain',
    myChains: 'My chains',
    compare: 'A1 ↔ C1',
    directory: 'L1 directory',
    explorer: 'Explorer',
    explorerAria: 'Open 9Scan-A1 in a new tab',
    ceremony: 'Ceremony',
    // Footer / cross-page labels for the three "About" pages — copied from each page's own
    // `title` on 2026-09-05, when English was split per page: the footer must not read a
    // page's group, or that page's whole text rides in every other page's bundle.
    validators: 'Run a validator',
    docs: 'Documentation',
    nineYears: 'Nine years, nine billion',
  },

  /** The language picker. See `components/LanguagePicker.tsx` for the reasoning behind each label. */
  langPicker: {
    label: 'Language',
    machineBadge: 'machine',
    machineNote: 'Only Vietnamese has been reviewed by a person. The other translations are machine-made and may be wrong — the English version is the source of truth.',
    notAvailable: 'not yet available',
  },

  errors: {
    unreachable: 'Could not reach the network',
    unreachableDesc: 'The network may be busy, or your connection may have dropped.',
    empty: 'Nothing here yet',
    addressEmpty: '{label} must not be empty',
    addressFormat: '{label} must be 0x followed by 40 hex characters',
    addressChecksum: '{label} fails its EIP-55 checksum — most likely one character was mistyped or lost when pasting',
    addressZero: '{label} must not be the zero address — nobody holds its key',
    timeout: 'No answer after {seconds}s',
    notJson: 'The answer was not JSON (HTTP {status}) — most likely the request was routed to the wrong place',
    noWallet: 'No wallet found in this browser.',
  },

  loadTest: {
    badge: 'Load test',
    banner: 'We are running a public load test — {tps} transactions per second, generated by us, not real users.',
    bannerLink: 'See the live numbers',

    title: 'Public load test',
    intro:
      'A1 is a young test network with very few real users, so left alone it produces almost no ' +
      'blocks. We generate a steady stream of transactions so the network is continuously ' +
      'exercised and so you can watch it work. This traffic is ours. It is not usage, and we do ' +
      'not count it as usage — every address sending it is listed below so you can subtract it.',

    running: 'Running now',
    stopped: 'Not running right now',
    stoppedWhy: 'Reason recorded: {reason}',

    labelTps: 'Transactions per second',
    labelBlockHeight: 'C-Chain block',
    labelSecondsPerBlock: 'Seconds per block',
    labelTotal: 'Transactions confirmed since start',
    labelUptime: 'Running for',

    committedNote:
      'These figures are counted from the blocks themselves, not from what we tried to send. ' +
      'A transaction the network accepted but never included in a block is not counted here.',

    addressesTitle: 'The nine sending addresses',
    addressesNote:
      'Every transaction from these addresses is machine-generated by us. Filter them out to see ' +
      'whatever real activity exists.',

    measuring: 'Reading the load test status…',
    notMeasured: 'Could not read the load test status',
    notMeasuredMore: 'The page still works — this is only the status display.',
  },

  // In the core, not in a page file: Next mounts the not-found boundary into EVERY page's
  // shared bundle (the `/_not-found` route's first load is the shared chunks plus 126 B), so
  // `check-en-split` measured this group on all 13 pages when it had a file of its own.
  notFound: {
    code: '404',
    title: 'This page does not exist',
    desc:
      'The address you opened does not exist on 9Chain Testnet A1. ' +
      'It may have been renamed, or the URL may have lost a few characters when it was copied.',
    topPagesTitle: 'The three most used pages:',
    navLabel: 'Where to go next',
    goHome: 'Back to home',
    goFaucet: 'Get test tokens',
    goLaunch: 'Launch your chain',
    lookingForTx: 'Looking for a transaction or an address? Check the hash and try again.',
  },
};

/** The shape of the core alone — what `useT()` hands to every component. */
export type Core = typeof EN_CORE;
