#!/usr/bin/env bash
# Give every VM plugin process a Go memory limit, without touching the fork.
#
# WHY THIS EXISTS
#   avalanchego starts one subnet-evm plugin per tracked chain, and builds that subprocess's
#   environment FROM EMPTY: vms/rpcchainvm/runtime/subprocess/runtime.go forwards only variables
#   prefixed GRPC_ or GODEBUG. So GOMEMLIMIT set on the container reaches avalanchego and NOT the
#   plugins — which hold the larger half of a node's memory (measured 2026-09-08 on the drill band:
#   923 MiB across 8 plugins against 628 MiB for avalanchego). Go does not read the cgroup limit,
#   so a plugin with no GOMEMLIMIT sizes its heap from GOGC alone.
#
#   Fixing runtime.go would mean regenerating the whole patch set, the fork tree and the image
#   (hard rule 3). This does the same job one layer out: a wrapper named exactly like the plugin,
#   in a directory handed to the node with --plugin-dir, which exports the limit and then execs the
#   real binary. Reversible, and it leaves no extra process behind.
#
#   🔴 The wrapper directory must contain NOTHING but wrappers. vms/registry/vm_getter.go:86 turns
#   any file whose name is not a valid VM ID into a hard error, and the node then does not start.
#
# Usage:
#   scripts/15-plugin-memlimit.sh --out <dir> --limit 300MiB [--container <name>] [--plugin-dir <path>]
#
# Then run the nodes with that directory mounted read-only and AVAGO_PLUGIN_DIR pointing at it, and
# prove the result in the processes themselves:
#   node scripts/check-plugin-memlimit.mjs --compose <compose file> --expect <node limit>
set -uo pipefail

OUT=""; LIMIT=""; CONTAINER="9chain-a1-tap-node-1"; PLUGIN_DIR="/9chain-a1/build/plugins"
while [ $# -gt 0 ]; do
  case "$1" in
    --out) OUT="${2:-}"; shift 2;;
    --limit) LIMIT="${2:-}"; shift 2;;
    --container) CONTAINER="${2:-}"; shift 2;;
    --plugin-dir) PLUGIN_DIR="${2:-}"; shift 2;;
    *) echo "unknown argument: $1" >&2; exit 2;;
  esac
done
[ -n "$OUT" ] || { echo "--out <dir> is required" >&2; exit 2; }
[ -n "$LIMIT" ] || { echo "--limit <value> is required, e.g. 300MiB" >&2; exit 2; }
case "$LIMIT" in
  *[!0-9BKMGTiB.]*|"") echo "--limit must be a Go memory limit such as 300MiB or 1GiB, got: $LIMIT" >&2; exit 2;;
esac

# Read the plugin names from the image itself rather than hardcoding a VM ID: a fork that rebuilds
# subnet-evm changes the ID, and a stale constant here would silently wrap nothing.
names=$(MSYS_NO_PATHCONV=1 docker exec "$CONTAINER" sh -c "ls -1 '$PLUGIN_DIR' 2>/dev/null") || {
  echo "could not list $PLUGIN_DIR inside $CONTAINER" >&2; exit 2; }
[ -n "$names" ] || { echo "no plugin found in $PLUGIN_DIR inside $CONTAINER" >&2; exit 2; }

mkdir -p "$OUT" || exit 2
# Anything already in there that is not one of the plugins would stop the node from booting.
for existing in "$OUT"/*; do
  [ -e "$existing" ] || continue
  base=$(basename "$existing")
  printf '%s\n' "$names" | grep -qx "$base" || { echo "refusing to write: $OUT holds $base, which is not a plugin name — the node would not boot" >&2; exit 2; }
done

count=0
while IFS= read -r name; do
  [ -n "$name" ] || continue
  target="$OUT/$name"
  {
    echo '#!/bin/sh'
    echo "# Generated by 15-plugin-memlimit.sh — do not edit by hand."
    echo "# avalanchego gives a plugin an environment built from empty, so the limit is set here."
    echo "GOMEMLIMIT=$LIMIT"
    echo "export GOMEMLIMIT"
    echo "exec \"$PLUGIN_DIR/$name\" \"\$@\""
  } > "$target" || exit 2
  chmod +x "$target" || exit 2
  count=$((count + 1))
  echo "  wrapper $name -> GOMEMLIMIT=$LIMIT"
done <<< "$names"

echo "$count wrapper(s) in $OUT"
echo "mount it read-only and set AVAGO_PLUGIN_DIR to the mount point, then check the processes:"
echo "  node scripts/check-plugin-memlimit.mjs --compose <compose file> --expect-plugin $LIMIT"
