#!/usr/bin/env bash
# Bring the drill-band cluster up: the netgen compose layered with the l1-batch override.
#
# Project name is pinned (-p k1p0) so volumes and the network never collide with the
# live local-net stack on the same Docker host. Host API ports come from the override
# (9750/9760/9770), NOT 9650 — the local explorer indexes 9650, and a drill chain that
# gets indexed then vanishes is the trap the drill compose already documents.
#
# Usage: scripts/up.sh            (base compose only, no ledgers tracked yet)
#        scripts/up.sh --k1       (base + out/plan/docker-compose.k1.yml after `render`)
set -euo pipefail
cd "$(dirname "$0")/.."
mkdir -p out/plan
FILES=(-f out/net/docker-compose.multinode.yml)
if [ "${1:-}" = "--k1" ]; then
  [ -f out/plan/docker-compose.k1.yml ] || { echo "✗ out/plan/docker-compose.k1.yml missing — run l1-batch render first" >&2; exit 1; }
  FILES+=(-f out/plan/docker-compose.k1.yml)
else
  # Without the override the netgen compose names image :dev, which this machine does not have.
  [ -f out/plan/docker-compose.base.yml ] || cat > out/plan/docker-compose.base.yml <<'EOF'
# Generated by scripts/up.sh — image + host ports for the bare cluster (before any ledger exists).
services:
  9chain-a1-tap-node-1: { image: 9chain-a1/node:g1-81, ports: !override ["127.0.0.1:9750:9650"] }
  9chain-a1-tap-node-2: { image: 9chain-a1/node:g1-81, ports: !override ["127.0.0.1:9760:9650"] }
  9chain-a1-tap-node-3: { image: 9chain-a1/node:g1-81, ports: !override ["127.0.0.1:9770:9650"] }
EOF
  FILES+=(-f out/plan/docker-compose.base.yml)
fi
# The env file netgen wrote (A1_CONFIG_DIR etc.) must be passed explicitly: compose only reads
# .env from the project directory, and ours lives next to the compose file.
MSYS_NO_PATHCONV=1 docker compose -p k1p0 --env-file out/net/.env "${FILES[@]}" up -d
echo "waiting for node1 health…"
for i in $(seq 1 60); do
  if curl -fsS -X POST -H 'content-type:application/json' \
       --data '{"jsonrpc":"2.0","id":1,"method":"info.isBootstrapped","params":{"chain":"P"}}' \
       http://127.0.0.1:9750/ext/info 2>/dev/null | grep -q '"isBootstrapped":true'; then
    echo "✓ node1 P-Chain bootstrapped after ~$((i*5))s"; exit 0
  fi
  sleep 5
done
echo "✗ node1 did not bootstrap P-Chain in 300s — docker compose -p k1p0 logs" >&2
exit 1
