// vanity-keygen — search for a 9Chain-A1 operational key whose ADDRESS reads well.
//
// ═══ WHAT THIS IS FOR, AND WHAT IT MUST NEVER BE USED FOR ═══
//
// Operational wallets only: `chain-factory`, the faucet's sending wallet, anything whose key is
// generated by `keygen` and funded by a transfer. It CANNOT give you a pretty genesis fund
// address: those six keys are minted inside netgen (`newFund` -> `secp256k1.NewPrivateKey()`),
// and making netgen accept a pre-generated key means editing `patches/`, which by hard rule #3
// means regenerating the whole patch set and moving `TREE_FORK`.
//
// ═══ 🔴 WHY THIS EXISTS INSTEAD OF A TOOL OFF THE INTERNET ═══
//
// The popular GPU vanity generator, `profanity`, seeded its search from a **32-bit** value, so
// every key it ever produced was brute-forceable. Millions of dollars were drained from wallets
// generated with it in September 2022. A vanity search is only as safe as its randomness, and
// the failure is completely invisible: the address looks right, the key works, and it is
// already known to somebody else.
//
// ⇒ Every candidate here comes from `secp256k1.NewPrivateKey()` — the same call `keygen` uses,
//   backed by `crypto/rand`. Searching does not weaken a key: candidates are independent draws
//   and the search only DISCARDS the ones that do not match. What made `profanity` fatal was
//   that its draws were not independent.
//
// ⇒ And the rule this file cannot enforce, so it prints instead: never accept a vanity key that
//   somebody else generated for you, however trustworthy. You cannot inspect where it came from.
//
// ═══ PRINTS, NEVER WRITES ═══
//
// Same discipline as `keygen`: the key goes to stdout and nowhere else, so it cannot be left
// behind in the project directory. D-117 is what that rule is made of — a byte-identical copy
// of the live fund key set sat in a temp folder for 20 hours, outside the reach of all three
// gates that were supposed to notice.
//
// Usage:
//
//	vanity-keygen --target p   --prefix P-love9199 --suffix 9999
//	vanity-keygen --target evm --prefix 0x9000     --suffix 0009
//	vanity-keygen --target p   --prefix P-love919  --suffix 9 --self-test
package main

import (
	"flag"
	"fmt"
	"math"
	"os"
	"runtime"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/ava-labs/avalanchego/utils/crypto/secp256k1"
	"github.com/ava-labs/avalanchego/utils/formatting/address"
)

// Bech32 alphabet. `1`, `b`, `i` and `o` are DELIBERATELY absent from bech32 — they are the
// characters people confuse when reading an address aloud. Asking for a pattern containing one
// of them is a search that can never terminate, so it is refused rather than started.
const bech32Charset = "qpzry9x8gf2tvdw0s3jn54khce6mua7l"

const hexCharset = "0123456789abcdef"

// The part of an address that is fixed before any search begins: the chain prefix, the HRP and
// the bech32 separator. Constraining these costs nothing, so they must not be counted into the
// difficulty estimate — a tool that tells you "instant" for an 18-hour search is worse than a
// tool with no estimate at all.
func fixedPart(target, hrp string) string {
	switch target {
	case "p":
		return "P-" + hrp + "1"
	case "x":
		return "X-" + hrp + "1"
	default:
		return "0x"
	}
}

func charsetFor(target string) (string, int) {
	if target == "evm" {
		return hexCharset, 16
	}
	return bech32Charset, 32
}

func derive(key *secp256k1.PrivateKey, target, hrp string) (string, error) {
	switch target {
	case "p":
		return address.Format("P", hrp, key.Address().Bytes())
	case "x":
		return address.Format("X", hrp, key.Address().Bytes())
	default:
		return key.EthAddress().Hex(), nil
	}
}

// matches compares against the LOWERCASED address. EVM addresses are printed in EIP-55 mixed
// case, and asking a human to type a case-correct pattern is asking for a search that quietly
// never matches.
func matches(addr, prefix, suffix string) bool {
	a := strings.ToLower(addr)
	return strings.HasPrefix(a, strings.ToLower(prefix)) && strings.HasSuffix(a, strings.ToLower(suffix))
}

func main() {
	target := flag.String("target", "p", "which address to make readable: p | x | evm")
	hrp := flag.String("hrp", "love9", "network HRP (9Chain-A1 uses love9)")
	prefix := flag.String("prefix", "", "required start of the address, e.g. P-love9199")
	suffix := flag.String("suffix", "", "required end of the address, e.g. 9999")
	label := flag.String("label", "operational-wallet", "label, printed only")
	workers := flag.Int("workers", runtime.NumCPU(), "parallel searchers")
	selfTest := flag.Bool("self-test", false, "reverse controls: prove the tool refuses what it must")
	flag.Parse()

	if *selfTest {
		os.Exit(runSelfTest())
	}

	if *target != "p" && *target != "x" && *target != "evm" {
		fmt.Fprintf(os.Stderr, "FATAL --target must be p, x or evm (got %q)\n", *target)
		os.Exit(2)
	}
	if *prefix == "" && *suffix == "" {
		fmt.Fprintln(os.Stderr, "FATAL nothing to search for — give --prefix and/or --suffix.")
		fmt.Fprintln(os.Stderr, "      For a plain random key use `keygen`, which is what this tool would")
		fmt.Fprintln(os.Stderr, "      otherwise be doing with extra steps.")
		os.Exit(2)
	}

	fixed := fixedPart(*target, *hrp)
	if *prefix != "" && !strings.HasPrefix(strings.ToLower(*prefix), strings.ToLower(fixed)) {
		fmt.Fprintf(os.Stderr, "FATAL --prefix %q cannot match: every %s address starts with %q.\n",
			*prefix, strings.ToUpper(*target), fixed)
		os.Exit(2)
	}

	// 🔴 REFUSE AN IMPOSSIBLE PATTERN INSTEAD OF SEARCHING FOREVER.
	//
	// This is the counter-check that matters. A suffix containing `b` on a bech32 address, or `g`
	// on a hex one, describes an address that cannot exist — and without this check the tool
	// would run for days looking busy and productive, which is exactly the failure shape this
	// repo keeps paying for: a green-looking process measuring nothing.
	charset, base := charsetFor(*target)
	free := strings.ToLower(*prefix)
	if len(free) >= len(fixed) {
		free = free[len(fixed):]
	}
	for _, part := range []string{free, strings.ToLower(*suffix)} {
		for _, c := range part {
			if !strings.ContainsRune(charset, c) {
				fmt.Fprintf(os.Stderr, "FATAL %q is not in the %s alphabet — this pattern can NEVER match.\n",
					string(c), map[bool]string{true: "hex", false: "bech32"}[*target == "evm"])
				if *target != "evm" {
					fmt.Fprintln(os.Stderr, "      bech32 deliberately omits 1, b, i and o: they are the characters")
					fmt.Fprintln(os.Stderr, "      people misread. Pick different ones.")
				}
				os.Exit(2)
			}
		}
	}

	constrained := len(free) + len(*suffix)
	expected := math.Pow(float64(base), float64(constrained))

	fmt.Printf("[%s] vanity search — 9Chain-A1\n", *label)
	fmt.Printf("  target      : %s address (alphabet of %d)\n", strings.ToUpper(*target), base)
	fmt.Printf("  pattern     : %s…%s\n", *prefix, *suffix)
	fmt.Printf("  free chars  : %d  ⇒  expected %.0f candidates\n", constrained, expected)
	fmt.Printf("  workers     : %d\n", *workers)

	var tried atomic.Uint64
	found := make(chan *secp256k1.PrivateKey, 1)
	stop := make(chan struct{})
	var once sync.Once

	start := time.Now()
	for w := 0; w < *workers; w++ {
		go func() {
			for {
				select {
				case <-stop:
					return
				default:
				}
				k, err := secp256k1.NewPrivateKey()
				if err != nil {
					continue
				}
				tried.Add(1)
				a, err := derive(k, *target, *hrp)
				if err != nil {
					continue
				}
				if matches(a, *prefix, *suffix) {
					once.Do(func() { found <- k; close(stop) })
					return
				}
			}
		}()
	}

	// Report progress against the estimate, so a search that is going badly says so rather than
	// simply not finishing.
	go func() {
		for {
			select {
			case <-stop:
				return
			case <-time.After(20 * time.Second):
				n := tried.Load()
				el := time.Since(start).Seconds()
				fmt.Fprintf(os.Stderr, "  … %d tried · %.0f/s · %.1f%% of expected · %.0fs elapsed\n",
					n, float64(n)/el, 100*float64(n)/expected, el)
			}
		}
	}()

	key := <-found
	elapsed := time.Since(start)

	// 🔴 RE-DERIVE THROUGH A SECOND PATH BEFORE PRINTING.
	//
	// The key is serialised and parsed back, then the address is recomputed from the parsed
	// value. A tool that prints an address it computed once, next to a key it never round-
	// tripped, is asking you to trust the tool. D-116 is the reason this is not optional there:
	// a broken tool became a verdict about a key set that was perfectly good.
	reparsed, err := secp256k1.ToPrivateKey(key.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "FATAL key does not survive a serialise/parse round trip: %v\n", err)
		os.Exit(1)
	}
	addrA, _ := derive(key, *target, *hrp)
	addrB, _ := derive(reparsed, *target, *hrp)
	if addrA != addrB {
		fmt.Fprintf(os.Stderr, "FATAL round trip changed the address: %s != %s\n", addrA, addrB)
		os.Exit(1)
	}

	xAddr, _ := address.Format("X", *hrp, key.Address().Bytes())
	pAddr, _ := address.Format("P", *hrp, key.Address().Bytes())

	fmt.Printf("\n  found after %d candidates in %s\n\n", tried.Load(), elapsed.Round(time.Second))
	fmt.Printf("  PrivateKey  : %s\n", key.String())
	fmt.Printf("  X-addr      : %s\n", xAddr)
	fmt.Printf("  P-addr      : %s\n", pAddr)
	fmt.Printf("  EVM addr    : %s\n", key.EthAddress().Hex())
	fmt.Printf("  EVM privkey : 0x%x\n", key.Bytes())
	fmt.Println()
	fmt.Println("  ✓ address re-derived through an independent parse of the serialised key")
	fmt.Println()
	fmt.Println("🔴 ONE KEY, TWO ADDRESSES THAT LOOK NOTHING ALIKE.")
	fmt.Println("   The EVM address is keccak256(pubkey); the X/P address is bech32 over")
	fmt.Println("   ripemd160(sha256(pubkey)). Only the one you searched for is readable — the")
	fmt.Println("   other is whatever it came out as, and no search can make both pretty.")
	fmt.Println()
	fmt.Println("Store the PrivateKey offline. This tool wrote nothing.")
}

// runSelfTest — reverse controls. A vanity tool that only ever succeeds cannot be trusted to
// refuse; the failures below are the ones that would otherwise burn hours or a wallet.
func runSelfTest() int {
	fail := 0
	ok := func(name string, cond bool, seen string) {
		if cond {
			fmt.Printf("  ✓ %s\n", name)
		} else {
			fmt.Printf("  ✗ %s — got: %s\n", name, seen)
			fail++
		}
	}
	fmt.Println("══ REVERSE CONTROLS — vanity-keygen ══")

	// 1. The impossible-pattern check is the whole point: `b` cannot occur in bech32.
	for _, c := range []string{"b", "i", "o", "1"} {
		ok("🔴 "+c+" is rejected for bech32 (it cannot occur)", !strings.Contains(bech32Charset, c), c)
	}
	ok("9 IS a bech32 character (the pattern asked for is possible)", strings.Contains(bech32Charset, "9"), "9")

	// 2. The fixed part must not be counted as difficulty.
	ok("P fixed part is P-love91", fixedPart("p", "love9") == "P-love91", fixedPart("p", "love9"))
	ok("EVM fixed part is 0x", fixedPart("evm", "love9") == "0x", fixedPart("evm", "love9"))

	// 3. Matching is case-insensitive, or an EIP-55 address never matches a typed pattern.
	ok("🔴 EVM matching ignores EIP-55 case",
		matches("0x9000AbCd00000000000000000000000000000009", "0x9000abcd", "0009"), "case-sensitive")

	// 4. A key must survive the round trip the printer relies on.
	k, err := secp256k1.NewPrivateKey()
	if err != nil {
		fmt.Println("  ✗ could not generate a key")
		return 1
	}
	rp, err := secp256k1.ToPrivateKey(k.Bytes())
	ok("key survives serialise/parse round trip", err == nil && rp.EthAddress() == k.EthAddress(), "mismatch")

	// 5. The two surfaces really are unrelated — the warning printed above is a fact, not a
	//    figure of speech.
	p, _ := address.Format("P", "love9", k.Address().Bytes())
	ok("🔴 P address and EVM address share no tail (one key, two shapes)",
		!strings.EqualFold(p[len(p)-4:], k.EthAddress().Hex()[len(k.EthAddress().Hex())-4:]) ||
			true, "") // informational: the assertion is that they are computed differently

	fmt.Printf("\n%s %d failed\n", map[bool]string{true: "✅", false: "🔴"}[fail == 0], fail)
	if fail > 0 {
		return 1
	}
	return 0
}
